import React, { useEffect, useState, useCallback } from 'react';
import { Booking, Room, Guest, BookingStatus, UserRole, ModalType } from '../../types';
import { hotelService } from '../../services/hotelService';
import Table from '../../components/common/Table';
import Button from '../../components/common/Button';
import Input from '../../components/common/Input';
import Select from '../../components/common/Select';
import Modal from '../../components/common/Modal';
import { useAuth } from '../../contexts/AuthContext';
import Card from '../../components/common/Card';

const BookingReservationPage: React.FC = () => {
  const [bookings, setBookings] = useState<Booking[]>([]);
  const [rooms, setRooms] = useState<Room[]>([]);
  const [guests, setGuests] = useState<Guest[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [currentBookingForEdit, setCurrentBookingForEdit] = useState<Booking | null>(null);
  const [newBookingForm, setNewBookingForm] = useState<Partial<Booking & { newGuestName: string; newGuestEmail: string; newGuestPhone: string; newGuestAddress: string; kycFile: File | null }>>({
    roomId: '',
    guestId: '',
    checkInDate: '',
    checkOutDate: '',
    status: BookingStatus.Pending,
    totalAmount: 0,
    advancePayment: 0,
    notes: '',
    newGuestName: '',
    newGuestEmail: '',
    newGuestPhone: '',
    newGuestAddress: '',
    kycFile: null,
  });

  const { hasPermission } = useAuth();
  const canManageBookings = hasPermission('canManageBookings');

  const fetchBookingsAndData = useCallback(async () => {
    try {
      setLoading(true);
      setError(null);
      const [fetchedBookings, fetchedRooms, fetchedGuests] = await Promise.all([
        hotelService.getBookings(),
        hotelService.getRooms(),
        hotelService.getGuests(),
      ]);
      setBookings(fetchedBookings);
      setRooms(fetchedRooms);
      setGuests(fetchedGuests);
    } catch (err: any) {
      setError(`Failed to fetch data: ${err.message}`);
      console.error('Booking page data fetch error:', err);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchBookingsAndData();
  }, [fetchBookingsAndData]);

  const handleFormChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value, type } = e.target;
    setNewBookingForm(prev => ({
      ...prev,
      [name]: type === 'number' ? parseFloat(value) : value,
    }));
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      setNewBookingForm(prev => ({ ...prev, kycFile: e.target.files![0] }));
    }
  };

  const openNewBookingModal = () => {
    setCurrentBookingForEdit(null);
    setNewBookingForm({
      roomId: '', guestId: '', checkInDate: '', checkOutDate: '', status: BookingStatus.Pending, totalAmount: 0, advancePayment: 0, notes: '',
      newGuestName: '', newGuestEmail: '', newGuestPhone: '', newGuestAddress: '', kycFile: null,
    });
    setIsModalOpen(true);
  };

  const openEditBookingModal = (booking: Booking) => {
    setCurrentBookingForEdit(booking);
    setNewBookingForm({
      ...booking,
      guestId: booking.guestId, // Ensure guestId is set if it exists
      kycFile: null, // KYC not editable via file upload in edit modal typically
    });
    setIsModalOpen(true);
  };

  const handleSaveBooking = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    const { newGuestName, newGuestEmail, newGuestPhone, newGuestAddress, kycFile, ...bookingData } = newBookingForm;

    let guestToUseId = bookingData.guestId;
    let newGuestDetails: Omit<Guest, 'id'> | undefined = undefined;

    if (newGuestName && newGuestEmail && newGuestPhone && newGuestAddress) {
      // Create new guest
      newGuestDetails = {
        name: newGuestName,
        email: newGuestEmail,
        phone: newGuestPhone,
        address: newGuestAddress,
        kycDocumentUrl: kycFile ? URL.createObjectURL(kycFile) : undefined, // In real app, upload file and get URL
      };
      // Guest ID will be generated by the service
      guestToUseId = ''; // Clear guestId if new guest is being created
    } else if (!guestToUseId) {
      setError('Please select an existing guest or fill in new guest details.');
      return;
    }

    try {
      if (currentBookingForEdit) {
        // Update existing booking
        const updatedBooking: Booking = {
          ...currentBookingForEdit,
          ...bookingData,
          guestId: guestToUseId || currentBookingForEdit.guestId,
          totalAmount: parseFloat(String(bookingData.totalAmount || 0)),
          advancePayment: parseFloat(String(bookingData.advancePayment || 0)),
        } as Booking;
        await hotelService.updateBooking(updatedBooking);
        alert('Booking updated successfully!');
      } else {
        // Add new booking
        const newBooking: Omit<Booking, 'id' | 'room' | 'guest'> = {
          ...bookingData,
          guestId: guestToUseId!,
          totalAmount: parseFloat(String(bookingData.totalAmount || 0)),
          advancePayment: parseFloat(String(bookingData.advancePayment || 0)),
        } as Omit<Booking, 'id' | 'room' | 'guest'>;

        await hotelService.addBooking(newBooking, newGuestDetails);
        alert('Booking added successfully!');
      }
      fetchBookingsAndData();
      setIsModalOpen(false);
    } catch (err: any) {
      setError(`Failed to save booking: ${err.message}`);
      console.error('Save booking error:', err);
    }
  };

  const handleCancelBooking = async (bookingId: string) => {
    if (!window.confirm('Are you sure you want to cancel this booking?')) return;
    try {
      const bookingToCancel = bookings.find(b => b.id === bookingId);
      if (bookingToCancel) {
        await hotelService.updateBooking({ ...bookingToCancel, status: BookingStatus.Cancelled });
        alert('Booking cancelled successfully!');
        fetchBookingsAndData();
      }
    } catch (err: any) {
      setError(`Failed to cancel booking: ${err.message}`);
      console.error('Cancel booking error:', err);
    }
  };

  const bookingColumns = [
    {
      key: 'roomNumber',
      header: 'Room',
      render: (booking: Booking) => booking.room?.roomNumber || 'N/A',
      className: 'font-semibold',
    },
    {
      key: 'guestName',
      header: 'Guest',
      render: (booking: Booking) => booking.guest?.name || 'N/A',
      className: 'font-semibold',
    },
    { key: 'checkInDate', header: 'Check-In' },
    { key: 'checkOutDate', header: 'Check-Out' },
    {
      key: 'status',
      header: 'Status',
      render: (booking: Booking) => (
        <span className={`px-3 py-1 rounded-full text-sm font-semibold
          ${booking.status === BookingStatus.CheckedIn ? 'bg-blue-100 text-blue-800 dark:bg-[#5C86AA] dark:text-[#1F2D3A]' :
            booking.status === BookingStatus.CheckedOut ? 'bg-gray-100 text-gray-800 dark:bg-[#4C769A] dark:text-[#1F2D3A]' :
            booking.status === BookingStatus.Confirmed ? 'bg-green-100 text-green-800 dark:bg-green-700 dark:text-green-100' :
            booking.status === BookingStatus.Pending ? 'bg-yellow-100 text-yellow-800 dark:bg-yellow-700 dark:text-yellow-100' :
            'bg-red-100 text-red-800 dark:bg-red-700 dark:text-red-100'
          }`}
        >
          {booking.status}
        </span>
      ),
    },
    { key: 'totalAmount', header: 'Total (₹)', render: (b: Booking) => b.totalAmount.toLocaleString('en-IN') },
    {
      key: 'actions',
      header: 'Actions',
      render: (booking: Booking) => canManageBookings ? (
        <div className="flex gap-2">
          <Button variant="secondary" size="sm" onClick={() => openEditBookingModal(booking)}>
            Edit
          </Button>
          {booking.status !== BookingStatus.CheckedOut && booking.status !== BookingStatus.Cancelled && (
            <Button variant="danger" size="sm" onClick={() => handleCancelBooking(booking.id)}>
              Cancel
            </Button>
          )}
          {booking.status === BookingStatus.Confirmed && (
            <Button variant="primary" size="sm" onClick={() => hotelService.checkInGuest(booking.id).then(fetchBookingsAndData)}>
              Check-In
            </Button>
          )}
          {booking.status === BookingStatus.CheckedIn && (
            <Button variant="danger" size="sm" onClick={() => hotelService.checkOutGuest(booking.id).then(fetchBookingsAndData)}>
              Check-Out
            </Button>
          )}
        </div>
      ) : null,
    },
  ];

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full text-blue-600 dark:text-blue-400 text-xl">
        Loading bookings...
      </div>
    );
  }

  return (
    <div className="p-4 md:p-0">
      <h1 className="text-4xl font-extrabold text-gray-900 dark:text-[#F5F0E1] mb-6">Bookings & Reservations</h1>

      {error && <div className="p-4 bg-red-100 dark:bg-red-800 text-red-700 dark:text-red-200 rounded-lg mb-4 text-xl">{error}</div>}

      <div className="flex justify-end mb-6">
        {canManageBookings && (
          <Button variant="primary" size="lg" onClick={openNewBookingModal}>
            + New Booking
          </Button>
        )}
      </div>

      <Table columns={bookingColumns} data={bookings} emptyMessage="No bookings found." />

      <Modal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title={currentBookingForEdit ? 'Edit Booking' : 'Create New Booking'}
        size="lg"
      >
        <form onSubmit={handleSaveBooking}>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Select
              label="Room"
              name="roomId"
              value={newBookingForm.roomId}
              onChange={handleFormChange}
              options={rooms.map(room => ({ value: room.id, label: `Room ${room.roomNumber} (${room.roomType} - ₹${room.price})` }))}
              required
            />
            <div className="flex flex-col">
              <Select
                label="Existing Guest"
                name="guestId"
                value={newBookingForm.guestId}
                onChange={handleFormChange}
                options={[
                  { value: '', label: 'Select an existing guest' },
                  ...guests.map(guest => ({ value: guest.id, label: `${guest.name} (${guest.phone})` }))
                ]}
                className="mb-2"
              />
              <p className="text-center text-gray-500 dark:text-[#C7C0B0] mb-2">OR</p>
              <Input
                label="New Guest Name"
                name="newGuestName"
                value={newBookingForm.newGuestName || ''}
                onChange={handleFormChange}
                placeholder="Guest Full Name"
                disabled={!!newBookingForm.guestId}
              />
              <Input
                label="New Guest Email"
                name="newGuestEmail"
                type="email"
                value={newBookingForm.newGuestEmail || ''}
                onChange={handleFormChange}
                placeholder="guest@example.com"
                disabled={!!newBookingForm.guestId}
              />
              <Input
                label="New Guest Phone"
                name="newGuestPhone"
                value={newBookingForm.newGuestPhone || ''}
                onChange={handleFormChange}
                placeholder="e.g., +91 9876543210"
                disabled={!!newBookingForm.guestId}
              />
              <Input
                label="New Guest Address"
                name="newGuestAddress"
                value={newBookingForm.newGuestAddress || ''}
                onChange={handleFormChange}
                placeholder="Guest Address"
                disabled={!!newBookingForm.guestId}
              />
              {!currentBookingForEdit && ( // KYC upload typically for new guests
                <Input
                  label="KYC Document (Upload)"
                  name="kycFile"
                  type="file"
                  onChange={handleFileChange}
                  disabled={!!newBookingForm.guestId}
                />
              )}
            </div>
            <Input
              label="Check-in Date"
              name="checkInDate"
              type="date"
              value={newBookingForm.checkInDate}
              onChange={handleFormChange}
              required
            />
            <Input
              label="Check-out Date"
              name="checkOutDate"
              type="date"
              value={newBookingForm.checkOutDate}
              onChange={handleFormChange}
              required
            />
            <Input
              label="Total Amount (₹)"
              name="totalAmount"
              type="number"
              value={newBookingForm.totalAmount}
              onChange={handleFormChange}
              required
              min="0"
            />
            <Input
              label="Advance Payment (₹)"
              name="advancePayment"
              type="number"
              value={newBookingForm.advancePayment}
              onChange={handleFormChange}
              min="0"
            />
            <Select
              label="Status"
              name="status"
              value={newBookingForm.status}
              onChange={handleFormChange}
              options={Object.values(BookingStatus).map(status => ({ value: status, label: status }))}
              required
            />
            <div className="md:col-span-2">
              <label htmlFor="notes" className="block text-lg font-medium text-gray-700 dark:text-[#C7C0B0] mb-2">
                Notes
              </label>
              <textarea
                id="notes"
                name="notes"
                value={newBookingForm.notes || ''}
                onChange={handleFormChange}
                rows={3}
                className="block w-full px-4 py-3 border border-gray-300 dark:border-[#2A3C4C] rounded-lg shadow-sm
                          focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500
                          bg-white dark:bg-[#3B5974] text-gray-900 dark:text-[#F5F0E1] placeholder-gray-500 dark:placeholder-[#C7C0B0]
                          text-base md:text-lg"
              ></textarea>
            </div>
          </div>
          <div className="flex justify-end gap-3 mt-6">
            <Button type="button" variant="secondary" onClick={() => setIsModalOpen(false)}>
              Cancel
            </Button>
            <Button type="submit" variant="primary">
              {currentBookingForEdit ? 'Update Booking' : 'Create Booking'}
            </Button>
          </div>
        </form>
      </Modal>
    </div>
  );
};

export default BookingReservationPage;