
import { GoogleGenAI } from '@google/genai';
import { GEMINI_API_KEY } from '../constants';

// Ensure the API key is available
if (!GEMINI_API_KEY || GEMINI_API_KEY === 'YOUR_GEMINI_API_KEY_HERE') {
  console.warn('Gemini API key is not set. AI features will not function.');
}

export const geminiService = {
  // Function to generate text content using Gemini Flash
  generateText: async (prompt: string, systemInstruction?: string): Promise<string> => {
    if (!GEMINI_API_KEY || GEMINI_API_KEY === 'YOUR_GEMINI_API_KEY_HERE') {
      return Promise.resolve("Gemini API key not configured. Cannot process AI request.");
    }

    try {
      const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });
      const config = {
        model: 'gemini-2.5-flash',
        contents: prompt,
        config: systemInstruction ? { systemInstruction } : {},
      };
      
      const response = await ai.models.generateContent(config);
      return response.text || "No response generated from AI.";
    } catch (error) {
      console.error('Error calling Gemini API:', error);
      // Check for specific error messages to guide the user to select an API key
      if (error instanceof Error && error.message.includes("Requested entity was not found.")) {
        // This is a common error when the API key is not valid or not selected in the AI Studio environment
        return `Error: API Key issue. Please ensure you have selected a valid API key through the AI Studio interface. You can access billing information at ai.google.dev/gemini-api/docs/billing.`;
      }
      return `Failed to get response from AI: ${(error as Error).message || 'Unknown error'}.`;
    }
  },

  // Placeholder for future multi-modal interactions if needed
  // generateImageDescription: async (image: string, prompt: string): Promise<string> => {
  //   // Logic to send image and text to Gemini for description
  //   return "Image description generated by AI.";
  // },
};
